core/urls.py
from django.urls import path, include
from .views import (
    IndexView,
    ShopView,
    ContactView,
    ProductDetailView,
    CheckoutView,
    cart,
    cart_add,
    cart_remove,
    cart_increment,
    cart_decrement,
)

app_name = 'core'

urlpatterns = [
     path('', IndexView.as_view(), name='index'),
     path('shop/', ShopView.as_view(), name='shop'),
     path('contact/', ContactView.as_view(), name='contact'),
     path('detail_product/<slug>/',
          ProductDetailView.as_view(), name='detail_product'),
     path('cart/', cart, name='cart'),
     path('cart/cart-remove/<int:id>',
          cart_remove, name='cart-remove'),
     path('cart/cart-add/<int:id>', cart_add, name='cart-add'),
     path('cart/cart-increment/<int:id>',
          cart_increment, name='cart-increment'),
     path('cart/cart-decrement/<int:id>',
          cart_decrement, name='cart-decrement'),
     path('checkout/',CheckoutView.as_view(),name='checkout'),
]

ecomerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

core/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.shortcuts import reverse
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    discount_price = models.IntegerField(blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, blank=True, null=True)
    description = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    image = models.ImageField(upload_to='cover_product', null=True, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def get_price(self, *args, **kwargs):
        discount_price = self.discount_price
        price = self.price

        if(discount_price != None):
            discount = price * discount_price/100
            return price - discount
        else:
            return price

    def get_absolute_url(self):
        url = reverse("core:detail_product", kwargs={
            'slug': self.slug
        })
        return url

    def __str__(self):
        return self.name


class Cart(models.Model):
    creation_date = models.DateTimeField(verbose_name=_('creation date'))
    checked_out = models.BooleanField(
        default=False, verbose_name=_('checked out'))

    class Meta:
        verbose_name = _('cart')
        verbose_name_plural = _('carts')
        ordering = ('-creation_date',)

    def __unicode__(self):
        return unicode(self.creation_date)


class ItemManager(models.Manager):
    def get(self, *args, **kwargs):
        if 'product' in kwargs:
            kwargs['content_type'] = ContentType.objects.get_for_model(
                type(kwargs['product']))
            kwargs['object_id'] = kwargs['product'].pk
            del(kwargs['product'])
        return super(ItemManager, self).get(*args, **kwargs)

    def filter(self, *args, **kwargs):
        if 'product' in kwargs:
            kwargs['content_type'] = ContentType.objects.get_for_model(
                type(kwargs['product']))
            kwargs['object_id'] = kwargs['product'].pk
            del(kwargs['product'])
        return super(ItemManager, self).filter(*args, **kwargs)


class Item(models.Model):
    cart = models.ForeignKey(Cart, verbose_name=_(
        'cart'), on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name=_('quantity'))
    unit_price = models.DecimalField(
        max_digits=18, decimal_places=2, verbose_name=_('unit price'))
    # product as generic relation
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()

    objects = ItemManager()

    class Meta:
        verbose_name = _('item')
        verbose_name_plural = _('items')
        ordering = ('cart',)

    def __unicode__(self):
        return u'%d units of %s' % (self.quantity, self.product.__class__.__name__)

    def total_price(self):
        return self.quantity * self.unit_price
    total_price = property(total_price)

    # product
    def get_product(self):
        return self.content_type.get_object_for_this_type(pk=self.object_id)

    def set_product(self, product):
        self.content_type = ContentType.objects.get_for_model(type(product))
        self.object_id = product.pk

    product = property(get_product, set_product)

core/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, View, DetailView
from .models import Product, Category
from .filters import OrderProduct, SearchProduct
from django.contrib.auth.decorators import login_required
from .cart import Cart
from decimal import Decimal

# Create your views here.


class IndexView(ListView):
    model = Product
    context_object_name = 'product_list'
    template_name = "home/index.html"

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        product = Product.objects.all()
        data_search = SearchProduct(self.request.GET, queryset=product)
        cart = Cart(self.request)
        context.update({
            'category_list': Category.objects.all(),
            'data_search': data_search,
            'cart': cart,
        })
        return context


class ShopView(ListView):
    model = Product
    context_object_name = 'product_list'
    template_name = "home/shop.html"

    def get_context_data(self, **kwargs):
        context = super(ShopView, self).get_context_data(**kwargs)
        product = Product.objects.all()
        data_filter = OrderProduct(self.request.GET, queryset=product)
        data_search = SearchProduct(self.request.GET, queryset=product)
        cart = Cart(self.request)
        context.update({
            'category_list': Category.objects.all(),
            'data_filter': data_filter,
            'data_search': data_search,
            'cart': cart,
        })
        return context


class ContactView(View):
    def get(self, *args, **kwargs):
        return render(self.request, "home/contact.html")


class ProductDetailView(DetailView):
    model = Product
    context_object_name = 'product'
    template_name = "home/detail_product.html"

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        product = Product.objects.all()
        data_filter = OrderProduct(self.request.GET, queryset=product)
        data_search = SearchProduct(self.request.GET, queryset=product)
        cart = Cart(self.request)
        context.update({
            'category_list': Category.objects.all(),
            'data_filter': data_filter,
            'data_search': data_search,
            'cart': cart,
        })
        return context

class CheckoutView(View):
    def get(self, *args, **kwargs):
        return render(self.request, "home/checkout.html")

# Cart Proces
@login_required
def cart(request):
    cart = Cart(request)
    product = Product.objects.all()
    data_search = SearchProduct(request.GET, queryset=product)
    total = 0
    for item in cart:
        total += item.total_price

    context = {
        'cart': cart,
        'data_search': data_search,
        'total': total
    }
    return render(request, 'home/cart.html', context)


@login_required
def cart_add(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)

    cart.add(product, product.get_price())
    return redirect('core:cart')


@login_required
def cart_remove(request, id):
    product = Product.objects.get(id=id)
    cart = Cart(request)
    cart.remove(product)
    return redirect('core:cart')


@login_required
def cart_increment(request, id):
    product = Product.objects.get(id=id)
    quantity = 1
    cart = Cart(request)
    cart.increment(product, quantity)
    return redirect('core:cart')


@login_required
def cart_decrement(request, id):
    product = Product.objects.get(id=id)
    quantity = 1
    cart = Cart(request)
    cart.decrement(product, quantity)
    return redirect('core:cart')

templates/home/cart.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
<!-- Breadcrumbs -->
<div class="breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="bread-inner">
                    <ul class="bread-list">
                        <li><a href="index1.html">Home<i class="ti-arrow-right"></i></a></li>
                        <li class="active"><a href="blog-single.html">Cart</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Breadcrumbs -->

<!-- Shopping Cart -->
<div class="shopping-cart section">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <!-- Shopping Summery -->
                <table class="table shopping-summery">
                    <thead>
                        <tr class="main-hading">
                            <th>PRODUCT</th>
                            <th>NAME</th>
                            <th class="text-center">UNIT PRICE</th>
                            <th class="text-center">QUANTITY</th>
                            <th class="text-center">TOTAL</th>
                            <th class="text-center"><i class="ti-trash remove-icon"></i></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for value in cart %}
                        <tr>
                            <td class="image" data-title="No"><img src="{{ value.product.image.url }}" alt="#">
                            </td>
                            <td class="product-des" data-title="Description">
                                <p class="product-name"><a href="#">{{ value.product.name }}</a></p>
                                <p class="product-des">{{ value.product.description|truncatewords:60 }}</p>
                            </td>
                            <td class="price" data-title="Price"><span>{{ value.product.get_price|intcomma }} </span>
                            </td>
                            <td class="qty" data-title="Qty">
                                <!-- Input Order -->
                                <div class="input-group">
                                    <div class="button minus">
                                        <a href="{% url 'core:cart-decrement' value.object_id %}"
                                            class="btn btn-primary">
                                            <i class="ti-minus"></i>
                                        </a>
                                    </div>
                                    <input type="text" readonly class="input-number" value="{{ value.quantity }}">
                                    <div class="button plus">
                                        <a href="{% url 'core:cart-increment' value.object_id %}"
                                            class="btn btn-primary">
                                            <i class="ti-plus"></i>
                                        </a>
                                    </div>
                                </div>
                                <!--/ End Input Order -->
                            </td>
                            <td class="total-amount" data-title="Total"><span>{{ value.total_price|intcomma }}</span>
                            </td>
                            <td class="action" data-title="Remove"><a
                                    href="{% url 'core:cart-remove' value.object_id %}"><i
                                        class="ti-trash remove-icon"></i></a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <!--/ End Shopping Summery -->
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <!-- Total Amount -->
                <div class="total-amount">
                    <div class="row">
                        <div class="col-lg-8 col-md-5 col-12">

                        </div>
                        <div class="col-lg-4 col-md-7 col-12">
                            <div class="right">
                                <ul>
                                    <li>Cart Total<span>Rp. {{ total|intcomma }}</span></li>
                                </ul>
                                <div class="button5">
                                    <a href="{% url 'core:checkout' %}" class="btn">Checkout</a>
                                    <a href="{% url 'core:shop' %}" class="btn">Continue shopping</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--/ End Total Amount -->
            </div>
        </div>
    </div>
</div>
<!--/ End Shopping Cart -->
{% endblock %}

templates/home/detail_product.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
<!-- Breadcrumbs -->
<div class="breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="bread-inner">
                    <ul class="bread-list">
                        <li><a href="{% url 'core:index' %}">Home<i class="ti-arrow-right"></i></a></li>
                        <li class="active"><a href="#">Detail Product</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Breadcrumbs -->

<!-- Start Blog Single -->
<section class="blog-single section">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-12">
                <div class="blog-single-main">
                    <div class="row">
                        <div class="col-12">
                            <div class="image">
                                <img src="https://via.placeholder.com/950x460" alt="#">
                            </div>
                            <div class="blog-detail">
                                <h2 class="blog-title">{{ product.name }}</h2>
                                <div class="blog-meta">
                                    <span class="author">
                                        <a href="#">
                                            <i class="fa fa-user"></i>
                                            {{ product.user}}
                                        </a>
                                        <a href="#">
                                            <i class="fa fa-comments"></i>Comment (15)
                                        </a>
                                    </span>
                                </div>
                                <div class="content">
                                    <p>{{ product.description }}</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="comments">
                                <h3 class="comment-title">Comments (3)</h3>
                                <!-- Single Comment -->
                                <div class="single-comment">
                                    <img src="https://via.placeholder.com/80x80" alt="#">
                                    <div class="content">
                                        <h4>Alisa harm <span>At 8:59 pm On Feb 28, 2018</span></h4>
                                        <p>Enthusiastically leverage existing premium quality vectors with
                                            enterprise-wide innovation collaboration Phosfluorescently leverage others
                                            enterprisee Phosfluorescently leverage.</p>
                                        <div class="button">
                                            <a href="#" class="btn"><i class="fa fa-reply"
                                                    aria-hidden="true"></i>Reply</a>
                                        </div>
                                    </div>
                                </div>
                                <!-- End Single Comment -->
                                <!-- Single Comment -->
                                <div class="single-comment left">
                                    <img src="https://via.placeholder.com/80x80" alt="#">
                                    <div class="content">
                                        <h4>john deo <span>Feb 28, 2018 at 8:59 pm</span></h4>
                                        <p>Enthusiastically leverage existing premium quality vectors with
                                            enterprise-wide innovation collaboration Phosfluorescently leverage others
                                            enterprisee Phosfluorescently leverage.</p>
                                        <div class="button">
                                            <a href="#" class="btn"><i class="fa fa-reply"
                                                    aria-hidden="true"></i>Reply</a>
                                        </div>
                                    </div>
                                </div>
                                <!-- End Single Comment -->
                                <!-- Single Comment -->
                                <div class="single-comment">
                                    <img src="https://via.placeholder.com/80x80" alt="#">
                                    <div class="content">
                                        <h4>megan mart <span>Feb 28, 2018 at 8:59 pm</span></h4>
                                        <p>Enthusiastically leverage existing premium quality vectors with
                                            enterprise-wide innovation collaboration Phosfluorescently leverage others
                                            enterprisee Phosfluorescently leverage.</p>
                                        <div class="button">
                                            <a href="#" class="btn"><i class="fa fa-reply"
                                                    aria-hidden="true"></i>Reply</a>
                                        </div>
                                    </div>
                                </div>
                                <!-- End Single Comment -->
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="reply">
                                <div class="reply-head">
                                    <h2 class="reply-title">Leave a Comment</h2>
                                    <!-- Comment Form -->
                                    <form class="form" action="#">
                                        <div class="row">
                                            <div class="col-lg-6 col-md-6 col-12">
                                                <div class="form-group">
                                                    <label>Your Name<span>*</span></label>
                                                    <input type="text" name="name" placeholder="" required="required">
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-md-6 col-12">
                                                <div class="form-group">
                                                    <label>Your Email<span>*</span></label>
                                                    <input type="email" name="email" placeholder="" required="required">
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label>Your Message<span>*</span></label>
                                                    <textarea name="message" placeholder=""></textarea>
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <div class="form-group button">
                                                    <button type="submit" class="btn">Post comment</button>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                    <!-- End Comment Form -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-12">
                <div class="main-sidebar">
                    <!-- Single Widget -->
                    <div class="single-widget category">
                        {% if product.discount_price %}
                        <h5>
                            <span class="font-weight-light text-danger">
                                <del>Rp. {{ product.price|intcomma }}</del></span>
                            <span class="badge badge-warning">{{ product.discount_price }}%</span>
                        </h5>
                        {% endif %}
                        <h3>Rp. {{ product.get_price|intcomma }}</h3>

                        <a class="btn btn-warning text-white mt-5" href="{% url 'core:cart-add' product.id %}">Add to
                            cart
                            <i class="fa fa-shopping-cart"></i>
                        </a>
                    </div>
                    <!--/ End Single Widget -->
                    <!-- Single Widget -->
                    <div class="single-widget side-tags">
                        <h3 class="title">Categories</h3>
                        <ul class="tag">
                            {% for category in category_list %}
                            <li>
                                <form action="{% url 'core:shop' %}" method="get">
                                    <input type="checkbox" name="category" hidden value="{{ category.id }}"
                                        class="check-input" checked>
                                    <button type="submit">
                                        <a>{{ category.name }}</a>
                                    </button>
                                </form>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <!--/ End Single Widget -->
                </div>
            </div>
        </div>
    </div>
</section>
<!--/ End Blog Single -->
{% endblock %}

templates/navbar.html
{% load static %}

<!-- Header -->
<header class="header shop">
    <!-- Topbar -->
    <div class="topbar">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-12 col-12">
                    <!-- Top Left -->
                    <div class="top-left">
                        <ul class="list-main">
                            <li><i class="ti-email"></i> support@shophub.com</li>
                        </ul>
                    </div>
                    <!--/ End Top Left -->
                </div>
                <div class="col-lg-8 col-md-12 col-12">
                    <!-- Top Right -->
                    <div class="right-content">
                        <ul class="list-main">
                            {% if request.user.is_authenticated %}
                            <li><i class="ti-user"></i> <a href="#">My account</a></li>
                            <li><i class="ti-power-off"></i><a href="{% url 'account_logout' %}">Logout</a></li>
                            {% else %}
                            <li><i class="ti-power-off"></i><a href="{% url 'account_login' %}">Login</a></li>
                            <li><i class="ti-user"></i><a href="{% url 'account_signup' %}">Register</a></li>
                            {% endif %}
                        </ul>
                    </div>
                    <!-- End Top Right -->
                </div>
            </div>
        </div>
    </div>
    <!-- End Topbar -->
    <div class="middle-inner">
        <div class="container">
            <div class="row">
                <div class="col-lg-2 col-md-2 col-12">
                    <!-- Logo -->
                    <div class="logo">
                        <a href="{% url 'core:index' %}"><img src="{% static 'images/logo.png' %}" alt="logo"></a>
                    </div>
                    <!--/ End Logo -->
                    <!-- Search Form -->
                    <div class="search-top">
                        <div class="top-search"><a href="#0"><i class="ti-search"></i></a></div>
                        <!-- Search Form -->
                        <div class="search-top">
                            <form class="search-form" method="GET" action="{% url 'core:shop' %}">
                                {{data_search.form}}
                                <button value="search" type="submit"><i class="ti-search"></i></button>
                            </form>
                        </div>
                        <!--/ End Search Form -->
                    </div>
                    <!--/ End Search Form -->
                    <div class="mobile-nav"></div>
                </div>
                <div class="col-lg-8 col-md-7 col-12">
                    <div class="search-bar-top">
                        <div class="search-bar">
                            <form method="GET" action="{% url 'core:shop' %}">
                                {{data_search.form}}
                                <button class="btnn" type="submit"><i class="ti-search"></i></button>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-2 col-md-3 col-12">
                    <div class="right-bar">
                        <div class="sinlge-bar shopping">
                            <a href="{% url 'core:cart' %}" class="single-icon"><i class="ti-bag"></i> <span
                                    class="total-count">{{ cart.all_product }}</span></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Header Inner -->
    <div class="header-inner">
        <div class="container">
            <div class="cat-nav-head">
                <div class="row">
                    <div class="col-lg-9 col-12">
                        <div class="menu-area">
                            <!-- Main Menu -->
                            <nav class="navbar navbar-expand-lg">
                                <div class="navbar-collapse">
                                    <div class="nav-inner">
                                        <ul class="nav main-menu menu navbar-nav">
                                            <li class="active"><a href="{% url 'core:index' %}">Home</a></li>
                                            <li><a href="{% url 'core:shop' %}">Product</a></li>
                                            <li><a href="{% url 'core:contact' %}">Contact Us</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </nav>
                            <!--/ End Main Menu -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ End Header Inner -->
</header>
<!--/ End Header -->

templates/script.html
{% load static %}

<!-- Jquery -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.0.js' %}"></script>
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<!-- Popper JS -->
<script src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- Color JS -->
<script src="{% static 'js/colors.js' %}"></script>
<!-- Slicknav JS -->
<script src="{% static 'js/slicknav.min.js' %}"></script>
<!-- Owl Carousel JS -->
<script src="{% static 'js/owl-carousel.js' %}"></script>
<!-- Magnific Popup JS -->
<script src="{% static 'js/magnific-popup.js' %}"></script>
<!-- Waypoints JS -->
<script src="{% static 'js/waypoints.min.js' %}"></script>
<!-- Countdown JS -->
<script src="{% static 'js/finalcountdown.min.js' %}"></script>
<!-- Nice Select JS -->
<script src="{% static 'js/nicesellect.js' %}"></script>
<!-- Flex Slider JS -->
<script src="{% static 'js/flex-slider.js' %}"></script>
<!-- ScrollUp JS -->
<script src="{% static 'js/scrollup.js' %}"></script>
<!-- Onepage Nav JS -->
<script src="{% static 'js/onepage-nav.min.js' %}"></script>
<!-- Easing JS -->
<script src="{% static 'js/easing.js' %}"></script>
<!-- Active JS -->
<script src="{% static 'js/active.js' %}"></script>

templates/slider.html
<!-- Slider Area -->
<section class="hero-slider">
    <!-- Single Slider -->
    <div class="single-slider">
        <div class="container">
            <div class="row no-gutters">
                <div class="col-lg-9 offset-lg-3 col-12">
                    <div class="text-inner">
                        <div class="row">
                            <div class="col-lg-7 col-12">
                                <div class="hero-text">
                                    <h1><span>UP TO 50% OFF </span>Shirt For Man</h1>
                                    <p>Maboriosam in a nesciung eget magnae <br> dapibus disting tloctio in the find
                                        it pereri <br> odiy maboriosm.</p>
                                    <div class="button">
                                        <a href="#" class="btn">Shop Now!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ End Single Slider -->
</section>
<!--/ End Slider Area -->